[package]
name = "channel_switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2.4.1"
notify-rust = "4"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
input-linux = "0.6.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
device_query = "1.1.3"